### ISSUE TITLE
Remove "DTO" suffix from classes in com.tomtom.services.configuration.dto package

### ISSUE THREAD

**Issue by FedorRomanov** [tomtom-international/configuration-service#4]
Remove DTO suffix from classes like:
1. NodeDTO
2. ParameterDTO
3. e.t.c.

They are models for search result response representation . Suffix isn't necessary. That's is sufficient that:
1. classes are located in _com....dto_ package
2. classes extend `ApiDTO` parent

**Comment by rijnb** [comment]
You are right in that it isn't strictly necessary, but in that case the class names for the domain objects and DTO object would be the same. That violates the rules of code being unambiguously clear **at the point ** reading. If you'd see `Node` without a `DTO` suffix, you cannot tell what it is until you hoover over it and your IDE shows you what it is, or you look a t the `import` section.

This rule applies for all code, by the way. In principal, you should never have to scroll or use your mouse to find out what something means. So, class names should be unique (when possible), units of variables should be stated in the name (like `timeoutSecs` rather than `timeout`), etc.
